library(remotes)

install_version("withr", "2.1.0")
install_version("sf", "0.5-4")
install_version("raster", "2.5-8")
install_version("dplyr", "0.7.1")
install_version("geosphere", "1.5-5")
install_version("rgdal", "1.2-16")
install_version("pryr", "0.1.2")
install_version("tmap", "1.10", type = "source")
install_github("tidyverse/ggplot2")
